@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

AddressBook *-right-> "1" UniquePersonList



UniquePersonList -right-> Person


Person *---> Name
Person *---> Course
Person *---> Email
Person *---> Id
Person *---> Grade
Person *---> Attendance
Attendance -[dotted]-> "1" AttendanceStatus
Person *---> Participation
Participation -[dotted]-> "1" ParticipationStatus
Person *---> Note
Person *---> Phone
Person -[dotted]-> NameContainsKeywordPredicate
@enduml
